spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: testtest

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true