spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: testtest
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
  server:
    port: ${PORT:8080}

java:
  runtime:
    version: 11
#  http:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      enabled: true




blog:
  title: DevPub
  subtitle: Рассказы Разработчиков
  phone: +7 930 070-73-79
  email: pks52@mail.ru
  copyright: Киселев Михаил
  copyrightFrom: 2005
  global_setting:
    MULTIUSER_MODE: true
    POST_PREMODERATION: true
    STATISTICS_IS_PUBLIC: true
