spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: testtest
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create




blog:
  title: DevPub
  subtitle: Рассказы Разработчиков
  phone: +7 930 070-73-79
  email: pks52@mail.ru
  copyright: Киселев Михаил
  copyrightFrom: 2005
  MULTIUSER_MODE: false
  POST_PREMODERATION: true
  STATISTICS_IS_PUBLIC: true