spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mkinfo23_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: mkinfo23_db
    password: h37zwoR*


  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
  server:
    port: 8080

#  http:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      enabled: true




blog:
  title: DevPub
  subtitle: Рассказы Разработчиков
  phone: +7 930 070-73-79
  email: pks52@mail.ru
  copyright: Киселев Михаил
  copyrightFrom: 2005
  global_setting:
    MULTIUSER_MODE: true
    POST_PREMODERATION: true
    STATISTICS_IS_PUBLIC: true
