spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mkinfob2_bd?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${USERNAME}
    password: ${PASSWORD}
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL}
    test-connection: true
    properties:
      "mail.smtp.auth": true
      "mail.transport.protocol": ${MAIL_PROTOCOL}
      "mail.debug": false

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
server:
  port: ${PORT:8080}

#  http:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      enabled: true




blog:
  title: Blog Engine
  subtitle: Рассказы Разработчиков
  phone: +7 930 070-73-79
  email: pks52@mail.ru
  copyright: Киселев Михаил
  copyrightFrom: 2005
  global_setting:
    MULTIUSER_MODE: true
    POST_PREMODERATION: true
    STATISTICS_IS_PUBLIC: true
